import { states } from "../../utils/States";

// Fields used for client intake
export const clientIntakeFormConfig = [
  {
    category: "Client Intake Form",
    data: [
      { field: "name", type: "text", label: "Client Name", required: true },
      { field: "dob", type: "date", label: "Date of Birth", required: false },
      { field: "address", type: "text", label: "Address", required: false },
      { field: "city", type: "text", label: "City", required: false },
      {
        field: "state",
        type: "select",
        label: "State",
        required: false,
        options: states,
      },
      { field: "zip", type: "text", label: "Zip Code", required: false },
      { field: "phone", type: "tel", label: "Phone Number", required: false },
      { field: "email", type: "email", label: "Email", required: false },
    ],
  },

  {
    category: "Skincare",
    data: [
      {
        field: "skin concerns",
        type: "checkbox",
        label: "Skin Concerns",
        required: false,
        options: [
          "Acne",
          "Acne Scarring",
          "Age Spots",
          "Blackheads",
          "Body Acne",
          "Broken Blood Vessels",
          "Bumps on back of arms",
          "Cellulite",
          "Cysts/Nodules",
          "Dehydrated Skin",
          "Dull Complexion",
          "Excessive Facial Hair",
          "Facial Veins",
          "Fine Lines/Wrinkles",
          "Frequent Breakouts",
          "Large Pores",
          "Loss of Lashes/Brows",
          "Melasma/Brown Spots/Patches",
          "Oily Skin",
          "Redness",
          "Rough/Uneven Skin Texture",
          "Rosacea",
          "Sagging Skin",
          "Sun Damage",
          "Under Eye Puffiness/Dark Circles",
          "Other",
        ],
      },
      {
        field: "skin type",
        type: "select",
        label: "Skin Type",
        required: true,
        options: ["Oily", "Dry", "Combination", "Sensitive"],
      },
      {
        field: "stress level",
        type: "select",
        label: "Stress Level",
        required: false,
        options: ["Little", "Moderate", "High", "Sever"],
      },
      {
        field: "overall health",
        type: "select",
        label: "Are you in good overall health?",
        required: false,
        options: ["Yes", "No"],
      },
    ],
  },

  {
    category: "Medical",
    data: [
      {
        field: "physician",
        type: "select",
        label: "Are you currently under the care of a physician?",
        required: false,
        options: ["Yes", "No"],
      },
      { field: "allergies", type: "text", label: "Allergies", required: false },
      {
        field: "medications",
        type: "text",
        label: "Medications",
        required: false,
      },
      {
        field: "medical conditions",
        type: "text",
        label: "Medical Conditions",
        required: false,
      },
      {
        field: "ethnic background",
        type: "text",
        label: "Ethnic Background",
        required: false,
      },
      {
        field: "acne",
        type: "select",
        label: "How do you heal after an acne breakout, cut, or scratch?",
        required: false,
        options: ["No scar", "Red", "Brown (PIH)"],
      },
      {
        field: "smoker",
        type: "select",
        label: "Do you smoke?",
        required: false,
        options: ["Yes", "No"],
      },
      {
        field: "cold sore",
        type: "select",
        label: "Are you prone to cold sores?",
        required: false,
        options: ["Yes", "No"],
      },
      {
        field: "latex",
        type: "select",
        label: "Are you allergic to latex?",
        required: false,
        options: ["Yes", "No"],
      },
      {
        field: "tanning",
        type: "select",
        label: "Do you tan in the sun or in tanning beds/booths?",
        required: false,
        options: ["Yes", "No"],
      },
      {
        field: "skincare products",
        type: "checkbox",
        label: "Current Skincare Products",
        required: false,
        options: [
          "Cleanser",
          "Toner",
          "Serum",
          "Scrub",
          "Mast",
          "Eye Cream",
          "Moisturizer",
          "Sunscreen",
          "Self Tanner",
          "Concealer",
          "Makeup",
          "Other",
        ],
      },
      {
        field: "more info",
        type: "text",
        label: "More Information",
        required: false,
      },
    ],
  },
];
